// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udzwvlgiezkwvrodvong.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkend2bGdpZXprd3Zyb2R2b25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMTUwODMsImV4cCI6MjA3MDc5MTA4M30.g1MJJVqS2ChM8If-hm3clVVxbBI3aWLqyO_W69WeUxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});